/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/testing1.glb
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./models/testing1.glb')
  const { actions, names } = useAnimations(animations, group)
  console.log(names)


  useEffect(()=>{
    console.log("here")
    actions.idle.play();
  },[]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Ch46" geometry={nodes.Ch46.geometry} 
        material={materials.Ch46_body} rotation={[Math.PI / 2, 0, 0]} 
        scale={0.01} castShadow/>
      </group>
    </group>
  )
}

useGLTF.preload('./models/testing1.glb')
