/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 ./public/Joey.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Joey(props) {
  const { nodes, materials } = useGLTF('models/Joey.glb')
  return (
    <group {...props} dispose={null} >
      <group rotation={[Math.PI / 2, 0, 0]}>
        <primitive object={nodes.Origin} />
        <skinnedMesh geometry={nodes.mesh_0_batch.geometry} material={materials.tr0072_00_fi_bodyMat} skeleton={nodes.mesh_0_batch.skeleton} castShadow/>
        <skinnedMesh geometry={nodes.mesh_1_uniform.geometry} material={materials.tr0072_fi_00_headMat} skeleton={nodes.mesh_1_uniform.skeleton} castShadow/>
      </group>
      
    </group>
  )
}

useGLTF.preload('models/Joey.glb');
